# Generated by Django 3.0.11 on 2020-12-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201226_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sections',
            new_name='category',
        ),
    ]
