# Generated by Django 3.0.11 on 2020-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201226_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('tech', 'Tech'), ('education', 'Education'), ('health', 'Health')], default='fashion', max_length=10),
        ),
    ]
