# Generated by Django 3.0.11 on 2020-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201226_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('tech', 'Tech')], default='health', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
